# coding: utf-8

"""
    Superlink API

    API for Superlink  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from SuperlinkAPI.models.api_access_token_type import ApiAccessTokenType

class ApiAccessToken(BaseModel):
    """
    ApiAccessToken
    """
    created_at: Optional[StrictStr] = Field(None, alias="createdAt")
    id: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    type: Optional[ApiAccessTokenType] = None
    updated_at: Optional[StrictStr] = Field(None, alias="updatedAt")
    valid_from: Optional[StrictStr] = Field(None, alias="validFrom")
    valid_till: Optional[StrictStr] = Field(None, alias="validTill")
    value: Optional[StrictStr] = None
    __properties = ["createdAt", "id", "label", "type", "updatedAt", "validFrom", "validTill", "value"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiAccessToken:
        """Create an instance of ApiAccessToken from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiAccessToken:
        """Create an instance of ApiAccessToken from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiAccessToken.parse_obj(obj)

        _obj = ApiAccessToken.parse_obj({
            "created_at": obj.get("createdAt"),
            "id": obj.get("id"),
            "label": obj.get("label"),
            "type": obj.get("type"),
            "updated_at": obj.get("updatedAt"),
            "valid_from": obj.get("validFrom"),
            "valid_till": obj.get("validTill"),
            "value": obj.get("value")
        })
        return _obj

