# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.1
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.api_wallet_login_request import ApiWalletLoginRequest

class TestApiWalletLoginRequest(unittest.TestCase):
    """ApiWalletLoginRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiWalletLoginRequest:
        """Test ApiWalletLoginRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiWalletLoginRequest`
        """
        model = ApiWalletLoginRequest()
        if include_optional:
            return ApiWalletLoginRequest(
                message = 'Sign this message for authorization to log in to superlink
OwnerAddress: 0xA5D70E12348Fef6A123EBD1231b123c51235E321
CreationTime: 2006-01-02T15:04:05-0700
ExpiryTime: 2006-01-02T15:04:05-0700
UniqueSignature: KCJuYW1lIjoiYWJjLmRlZi5naGkiLCJkYXRlIjoiMjAyMS0xMS0xMSIp',
                redirect_url = 'https://superlink.me/superlinks',
                signed_message = '0x1234567890abcdef1234567890abcdef12345678'
            )
        else:
            return ApiWalletLoginRequest(
        )
        """

    def testApiWalletLoginRequest(self):
        """Test ApiWalletLoginRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
