# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.2
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.api_sub_domain_available_response import ApiSubDomainAvailableResponse

class TestApiSubDomainAvailableResponse(unittest.TestCase):
    """ApiSubDomainAvailableResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiSubDomainAvailableResponse:
        """Test ApiSubDomainAvailableResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiSubDomainAvailableResponse`
        """
        model = ApiSubDomainAvailableResponse()
        if include_optional:
            return ApiSubDomainAvailableResponse(
                domain = 'test1.test.eth',
                status = 'available'
            )
        else:
            return ApiSubDomainAvailableResponse(
        )
        """

    def testApiSubDomainAvailableResponse(self):
        """Test ApiSubDomainAvailableResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
