# coding: utf-8

"""
    Superlink

    API for Superlink  # noqa: E501

    The version of the OpenAPI document: v0.1.15
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import superlink
from superlink.models.api_coin import ApiCoin  # noqa: E501
from superlink.rest import ApiException

class TestApiCoin(unittest.TestCase):
    """ApiCoin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiCoin(self):
        """Test ApiCoin"""
        # inst = ApiCoin()

if __name__ == '__main__':
    unittest.main()
