# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.2
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.api_sub_domain_total_response import ApiSubDomainTotalResponse

class TestApiSubDomainTotalResponse(unittest.TestCase):
    """ApiSubDomainTotalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiSubDomainTotalResponse:
        """Test ApiSubDomainTotalResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiSubDomainTotalResponse`
        """
        model = ApiSubDomainTotalResponse()
        if include_optional:
            return ApiSubDomainTotalResponse(
                count = 28
            )
        else:
            return ApiSubDomainTotalResponse(
        )
        """

    def testApiSubDomainTotalResponse(self):
        """Test ApiSubDomainTotalResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
