# coding: utf-8

"""
    Superlink

    API for Superlink  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import Superlink
from Superlink.models.api_access_token_type import ApiAccessTokenType  # noqa: E501
from Superlink.rest import ApiException

class TestApiAccessTokenType(unittest.TestCase):
    """ApiAccessTokenType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiAccessTokenType(self):
        """Test ApiAccessTokenType"""
        # inst = ApiAccessTokenType()

if __name__ == '__main__':
    unittest.main()
