# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.2
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.data_access_token_type import DataAccessTokenType

class TestDataAccessTokenType(unittest.TestCase):
    """DataAccessTokenType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataAccessTokenType(self):
        """Test DataAccessTokenType"""
        # inst = DataAccessTokenType()

if __name__ == '__main__':
    unittest.main()
