# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.3.28
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from superlink.models.api_coin import ApiCoin  # noqa: E501

class TestApiCoin(unittest.TestCase):
    """ApiCoin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiCoin(self):
        """Test ApiCoin"""
        # inst = ApiCoin()

if __name__ == '__main__':
    unittest.main()
