# coding: utf-8

"""
    Superlink

    API for Superlink  # noqa: E501

    The version of the OpenAPI document: v0.1.6
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import superlink
from superlink.models.api_name_service import ApiNameService  # noqa: E501
from superlink.rest import ApiException

class TestApiNameService(unittest.TestCase):
    """ApiNameService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiNameService(self):
        """Test ApiNameService"""
        # inst = ApiNameService()

if __name__ == '__main__':
    unittest.main()
