# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.2
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.api.resolution_api import ResolutionApi


class TestResolutionApi(unittest.TestCase):
    """ResolutionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResolutionApi()

    def tearDown(self) -> None:
        pass

    def test_resolve_data_by_address(self) -> None:
        """Test case for resolve_data_by_address

        Resolves wallets and DNS records for an address
        """
        pass

    def test_resolve_data_by_domain(self) -> None:
        """Test case for resolve_data_by_domain

        Resolves wallets and DNS records for a domain
        """
        pass


if __name__ == '__main__':
    unittest.main()
