# coding: utf-8

"""
    Superlink

    API for Superlink  # noqa: E501

    The version of the OpenAPI document: dev
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import Superlink
from Superlink.models.data_access_token_type import DataAccessTokenType  # noqa: E501
from Superlink.rest import ApiException

class TestDataAccessTokenType(unittest.TestCase):
    """DataAccessTokenType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataAccessTokenType(self):
        """Test DataAccessTokenType"""
        # inst = DataAccessTokenType()

if __name__ == '__main__':
    unittest.main()
