# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.3.30
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from superlink.models.api_market_purchase_response import ApiMarketPurchaseResponse

class TestApiMarketPurchaseResponse(unittest.TestCase):
    """ApiMarketPurchaseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiMarketPurchaseResponse:
        """Test ApiMarketPurchaseResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiMarketPurchaseResponse`
        """
        model = ApiMarketPurchaseResponse()
        if include_optional:
            return ApiMarketPurchaseResponse(
                checkout_id = '92353d2b-c3f5-4b3b-b214-c34b490b7324',
                order_id = '92456d2b-c315-4b2b-b234-c674490b7324',
                stripe_customer_id = 'cus_1234567890abcdef1234567890abcdef',
                stripe_ephemeral_key = 'ek_test_1234567890abcdef1234567890abcdef',
                stripe_payment_intent = 'pi_1234567890abcdef1234567890abcdef',
                stripe_publishable_key = 'pk_test_1234567890abcdef1234567890abcdef'
            )
        else:
            return ApiMarketPurchaseResponse(
        )
        """

    def testApiMarketPurchaseResponse(self):
        """Test ApiMarketPurchaseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
