# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.2
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.api_hns_register_tld_request import ApiHNSRegisterTLDRequest

class TestApiHNSRegisterTLDRequest(unittest.TestCase):
    """ApiHNSRegisterTLDRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiHNSRegisterTLDRequest:
        """Test ApiHNSRegisterTLDRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiHNSRegisterTLDRequest`
        """
        model = ApiHNSRegisterTLDRequest()
        if include_optional:
            return ApiHNSRegisterTLDRequest(
                partner_id = '248b8553-effa-4d99-a906-041a54f7df87',
                tld = 'com'
            )
        else:
            return ApiHNSRegisterTLDRequest(
        )
        """

    def testApiHNSRegisterTLDRequest(self):
        """Test ApiHNSRegisterTLDRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
