# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.1
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.api_subdomain_status import ApiSubdomainStatus

class TestApiSubdomainStatus(unittest.TestCase):
    """ApiSubdomainStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiSubdomainStatus(self):
        """Test ApiSubdomainStatus"""
        # inst = ApiSubdomainStatus()

if __name__ == '__main__':
    unittest.main()
