# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.1
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.api_sub_domain_item import ApiSubDomainItem

class TestApiSubDomainItem(unittest.TestCase):
    """ApiSubDomainItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiSubDomainItem:
        """Test ApiSubDomainItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiSubDomainItem`
        """
        model = ApiSubDomainItem()
        if include_optional:
            return ApiSubDomainItem(
                created_timestamp = '2024-01-01 07:31:02.315',
                name = 'test.superlink.me'
            )
        else:
            return ApiSubDomainItem(
        )
        """

    def testApiSubDomainItem(self):
        """Test ApiSubDomainItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
