# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.1
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.api_market_search_request import ApiMarketSearchRequest

class TestApiMarketSearchRequest(unittest.TestCase):
    """ApiMarketSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiMarketSearchRequest:
        """Test ApiMarketSearchRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiMarketSearchRequest`
        """
        model = ApiMarketSearchRequest()
        if include_optional:
            return ApiMarketSearchRequest(
                addrs = [
                    superlink.models.api/address_record.api.AddressRecord(
                        addr = '0x1234567890abcdef1234567890abcdef12345678', 
                        coin_id = 60, )
                    ],
                query = 'john doe'
            )
        else:
            return ApiMarketSearchRequest(
        )
        """

    def testApiMarketSearchRequest(self):
        """Test ApiMarketSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
