# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.1
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.api.prove_api import ProveApi


class TestProveApi(unittest.TestCase):
    """ProveApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProveApi()

    def tearDown(self) -> None:
        pass

    def test_get_eth_wallet_message(self) -> None:
        """Test case for get_eth_wallet_message

        Get message which should be signed by an eth wallet as proof of ownership
        """
        pass


if __name__ == '__main__':
    unittest.main()
