# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.4.1
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.api_get_all_domains_response import ApiGetAllDomainsResponse

class TestApiGetAllDomainsResponse(unittest.TestCase):
    """ApiGetAllDomainsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiGetAllDomainsResponse:
        """Test ApiGetAllDomainsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiGetAllDomainsResponse`
        """
        model = ApiGetAllDomainsResponse()
        if include_optional:
            return ApiGetAllDomainsResponse(
                domains = [
                    superlink.models.api/domain_basic_information.api.DomainBasicInformation(
                        created_at = '2024-01-01 07:31:02.315', 
                        image = 'https://api.superlink.me/card-image/jon.johnson.svg', 
                        name = 'jon.johnson', 
                        status = 'Active', 
                        type = 'Superlink', )
                    ]
            )
        else:
            return ApiGetAllDomainsResponse(
        )
        """

    def testApiGetAllDomainsResponse(self):
        """Test ApiGetAllDomainsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
