# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.5.0
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superlink.models.api_parent_domain_purchase_request_domain_contact_details import ApiParentDomainPurchaseRequestDomainContactDetails

class TestApiParentDomainPurchaseRequestDomainContactDetails(unittest.TestCase):
    """ApiParentDomainPurchaseRequestDomainContactDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiParentDomainPurchaseRequestDomainContactDetails:
        """Test ApiParentDomainPurchaseRequestDomainContactDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiParentDomainPurchaseRequestDomainContactDetails`
        """
        model = ApiParentDomainPurchaseRequestDomainContactDetails()
        if include_optional:
            return ApiParentDomainPurchaseRequestDomainContactDetails(
                address1 = '15 Church St',
                address2 = 'Door 25, The building',
                city = 'New York',
                country = 'US',
                email = 'nora.miller@gmail.com',
                name_first = 'Nora',
                name_last = 'Miller',
                phone_country_code = '+1',
                phone_number = '1234123412',
                postal_code = '12345',
                state = 'CA'
            )
        else:
            return ApiParentDomainPurchaseRequestDomainContactDetails(
        )
        """

    def testApiParentDomainPurchaseRequestDomainContactDetails(self):
        """Test ApiParentDomainPurchaseRequestDomainContactDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
