# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.2.2
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import superlink
from superlink.models.api_purchase_request import ApiPurchaseRequest  # noqa: E501
from superlink.rest import ApiException

class TestApiPurchaseRequest(unittest.TestCase):
    """ApiPurchaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiPurchaseRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiPurchaseRequest`
        """
        model = superlink.models.api_purchase_request.ApiPurchaseRequest()  # noqa: E501
        if include_optional :
            return ApiPurchaseRequest(
                customer_email_address = 'example@gmail.com', 
                customer_name = 'John Doe', 
                domain = 'firstname.lastname', 
                owner_address = '0x1234567890abcdef1234567890abcdef12345678', 
                stripe_connected_account_id = 'acct_1J1Z2X2Y2Z2X2Y2Z'
            )
        else :
            return ApiPurchaseRequest(
        )
        """

    def testApiPurchaseRequest(self):
        """Test ApiPurchaseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
