# coding: utf-8

"""
    Superlink

    API for Superlink

    The version of the OpenAPI document: v0.5.0
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ApiSubdomainStatus(str, Enum):
    """
    ApiSubdomainStatus
    """

    """
    allowed enum values
    """
    AVAILABLE = 'available'
    UNAVAILABLE = 'unavailable'
    REVOKED = 'revoked'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApiSubdomainStatus from a JSON string"""
        return cls(json.loads(json_str))


