# coding: utf-8

# flake8: noqa

"""
    Superlink API

    API for Superlink  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@superlink.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


__version__ = "1.0.0"

# import apis into sdk package
from SuperlinkAPI.api.access_token_api import AccessTokenApi
from SuperlinkAPI.api.health_api import HealthApi
from SuperlinkAPI.api.resolution_api import ResolutionApi

# import ApiClient
from SuperlinkAPI.api_response import ApiResponse
from SuperlinkAPI.api_client import ApiClient
from SuperlinkAPI.configuration import Configuration
from SuperlinkAPI.exceptions import OpenApiException
from SuperlinkAPI.exceptions import ApiTypeError
from SuperlinkAPI.exceptions import ApiValueError
from SuperlinkAPI.exceptions import ApiKeyError
from SuperlinkAPI.exceptions import ApiAttributeError
from SuperlinkAPI.exceptions import ApiException

# import models into sdk package
from SuperlinkAPI.models.api_access_token import ApiAccessToken
from SuperlinkAPI.models.api_access_token_create_request import ApiAccessTokenCreateRequest
from SuperlinkAPI.models.api_access_token_delete_request import ApiAccessTokenDeleteRequest
from SuperlinkAPI.models.api_access_token_type import ApiAccessTokenType
from SuperlinkAPI.models.api_dns_record import ApiDNSRecord
from SuperlinkAPI.models.api_resolve_wallet_address_by_domain_response import ApiResolveWalletAddressByDomainResponse
from SuperlinkAPI.models.api_response_bad_request import ApiResponseBadRequest
from SuperlinkAPI.models.api_response_error import ApiResponseError
from SuperlinkAPI.models.api_response_internal_server_error import ApiResponseInternalServerError
